server:
  port: 2333
  address: 0.0.0.0

lavalink:
  server:
    password: ${LAVALINK_SERVER_PASSWORD:youshallnotpass}
    sources:
      # DESHABILITAR YouTube nativo - LavaSrc lo manejará completamente
      youtube: false
      bandcamp: false
      soundcloud: false
      twitch: false
      vimeo: false
      http: true
      local: false
    # Configuraciones optimizadas para mejor rendimiento
    bufferDurationMs: 400
    frameBufferDurationMs: 5000
    opusEncodingQuality: 10
    resamplingQuality: HIGH
    trackStuckThresholdMs: 10000
    useSeekGhosting: true
    playerUpdateInterval: 5  # Más frecuente para mejor sincronización
    filters:
      volume: true
      equalizer: true
      karaoke: true
      timescale: true
      tremolo: true
      vibrato: true
      distortion: true
      rotation: true
      channelMix: true
      lowPass: true
  plugins:
    # Usaremos exclusivamente LavaSrc (yt-dlp) para YouTube por compatibilidad máxima
    - dependency: com.github.topi314.lavasrc:lavasrc-plugin:4.8.0
      repository: https://maven.topi.wtf/releases

plugins:
  lavasrc:
    providers:
      - "ytsearch:%ISRC%"
      - "ytsearch:%QUERY%"  # HABILITADO para búsquedas generales
    sources:
      youtube: false # DESHABILITADO - forzar que YouTube lo maneje yt-dlp
      ytdlp: true    # HABILITADO - Fuente directa con yt-dlp
      spotify: false
      applemusic: false
      deezer: false
      yandexmusic: false
      flowerytts: false
      vkmusic: false
      tidal: false
      qobuz: false
      jiosaavn: false
    youtube:
      countryCode: "US"
      language: "en"
    ytdlp:
      path: "/usr/local/bin/yt-dlp"
      searchLimit: 10
      # Usar valores por defecto del plugin (maneja cookies/format internamente)
  # Nota: No configuramos el plugin oficial de YouTube; evitamos conflictos con yt-dlp

logging:
  level:
    root: INFO
    lavalink: INFO
    lavalink.server.io: WARN
    com.github.topi314.lavasrc: DEBUG



